# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHrmlogin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_hrmlogin(self):
    # Test name: hrm_login
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("https://opensource-demo.orangehrmlive.com/")
    # 2 | setWindowSize | 1376x784 |  | 
    self.driver.set_window_size(1376, 784)
    # 3 | click | css=#divUsername > .form-hint |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#divUsername > .form-hint").click()
    # 4 | click | id=txtUsername |  | 
    self.driver.find_element(By.ID, "txtUsername").click()
    # 5 | type | id=txtUsername | admin | 
    self.driver.find_element(By.ID, "txtUsername").send_keys("admin")
    # 6 | type | id=txtPassword | admin123 | 
    self.driver.find_element(By.ID, "txtPassword").send_keys("admin123")
    # 7 | click | id=btnLogin |  | 
    self.driver.find_element(By.ID, "btnLogin").click()
    # 8 | click | id=welcome |  | 
    self.driver.find_element(By.ID, "welcome").click()
    # 9 | click | linkText=Logout |  | 
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
